export const TRADES = [
  "C-02 Insulation",
  "C-05 Framing and Rough Carpentry",
  "C-06 Cabinet and Finish Carpentry",
  "C-07 Low Voltage",
  "C-08 Concrete",
  "C-09 Drywall",
  "C-10 Electrical",
  "C-12 Earthwork and Paving",
  "C-13 Fencing",
  "C-15 Flooring and Floor Covering",
  "C-16 Fire Protection",
  "C-17 Glazing and Window Installation",
  "C-20 HVAC",
  "C-21 Demolition",
  "C-22 Asbestos Abatement",
  "C-23 Ornamental Metal",
  "C-27 Landscaping",
  "C-29 Masonry",
  "C-33 Painting and Decorating",
  "C-35 Lathing and Plastering",
  "C-36 Plumbing",
  "C-39 Roofing",
  "C-43 Sheet Metal",
  "C-53 Swimming Pool",
  "C-54 Tile and Counter Top",
  "C-61 Limited Specialty",
  "C-62 Appliances",
  "C-63 Fireplace",
  "C-64 Handyman",
  "C-65 Construction Cleanup",
  "C-66 City Inspector",
  "C-67 Deputy Inspector",
  "C-68 Engineer Observer",
  "C-69 Deliveries",
  "C-70 Soil Engineer",
  "C-71 Surveyor",
  "C-72 Designer",
  "C-00 Job site closed",
  "CC Surface Restoration",
] as const;

export type Trade = (typeof TRADES)[number];
